import Image from "next/image";
import Portfolio from "./portfolio";
import Services from "./services";
import Port from "./port";

export const metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function Projects() {
  return (
    <div className="mt-[120px] ">
      <div className="text-white flex justify-between items-start px-14 ">
        <div className="flex flex-col items-start">
          <div className="flex items-center space-x-4">
            <span className="w-3 h-3 bg-white rounded-full"></span>
            <span className="text-left uppercase text-lg">Portfolio</span>
          </div>
          <h1 className="uppercase text-[80px] leading-tight mt-2">
            Featured Works
          </h1>
        </div>
      </div>

      
      <div className="mt-[40px] flex flex-wrap justify-between gap-8 max-w-[1440px] mx-auto px-14">
        {/* Project 1 */}
        <div className="flex-1 max-w-[50%] group">
          <a 
            href="https://example.com" 
            target="_blank" 
            rel="noopener noreferrer"
            className="block w-full h-[480px] border-2 border-gray-400 rounded-[8px] overflow-hidden"
          >
            <img 
              src="/assets/img.jpg" 
              alt="Project 1" 
              className="w-full h-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
            />
          </a>
          <div className="relative h-[48px] mt-4 overflow-hidden">
            <h3 className="absolute top-0 left-0 text-white text-[40px] font-semibold transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
            <h3 className="absolute top-full left-0 text-white text-[40px] font-semibold underline transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
          </div>
          <div className="flex gap-x-4 text-white text-[18px]">
            <p>UI / UX Design</p>
            <p>Product Thinking</p>
          </div>
        </div>

        {/* Project 2 */}
        <div className="flex-1 max-w-[50%] group">
          <a 
            href="https://example.com" 
            target="_blank" 
            rel="noopener noreferrer"
            className="block w-full h-[480px] border-2 border-gray-400 rounded-[8px] overflow-hidden"
          >
            <img 
              src="/assets/img2.jpg" 
              alt="Project 2" 
              className="w-full h-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
            />
          </a>
          <div className="relative h-[48px] mt-4 overflow-hidden">
            <h3 className="absolute top-0 left-0 text-white text-[40px] font-semibold transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
            <h3 className="absolute top-full left-0 text-white text-[40px] font-semibold underline transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
          </div>
          <div className="flex gap-x-4 text-white text-[18px]">
            <p>UI / UX Design</p>
            <p>Product Thinking</p>
          </div>
        </div>
      </div>

      <div className="mt-[40px] flex flex-wrap justify-between gap-8 max-w-[1440px] mx-auto px-14">
        {/* Project 3 */}
        <div className="flex-1 max-w-[50%] group">
          <a 
            href="https://example.com" 
            target="_blank" 
            rel="noopener noreferrer"
            className="block w-full h-[480px] border-2 border-gray-400 rounded-[8px] overflow-hidden"
          >
            <img 
              src="/assets/img.jpg" 
              alt="Project 3" 
              className="w-full h-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
            />
          </a>
          <div className="relative h-[48px] mt-4 overflow-hidden">
            <h3 className="absolute top-0 left-0 text-white text-[40px] font-semibold transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
            <h3 className="absolute top-full left-0 text-white text-[40px] font-semibold underline transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
          </div>
          <div className="flex gap-x-4 text-white text-[18px]">
            <p>UI / UX Design</p>
            <p>Product Thinking</p>
          </div>
        </div>

        {/* Project 4 */}
        <div className="flex-1 max-w-[50%] group">
          <a 
            href="https://example.com" 
            target="_blank" 
            rel="noopener noreferrer"
            className="block w-full h-[480px] border-2 border-gray-400 rounded-[8px] overflow-hidden"
          >
            <img 
              src="/assets/img3.jpg" 
              alt="Project 4" 
              className="w-full h-full object-cover transition-transform duration-500 ease-in-out group-hover:scale-105"
            />
          </a>
          <div className="relative h-[48px] mt-4 overflow-hidden">
            <h3 className="absolute top-0 left-0 text-white text-[40px] font-semibold transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
            <h3 className="absolute top-full left-0 text-white text-[40px] font-semibold underline transition-transform duration-300 group-hover:-translate-y-full">
              Micro-loans digitization
            </h3>
          </div>
          <div className="flex gap-x-4 text-white text-[18px]">
            <p>UI / UX Design</p>
            <p>Product Thinking</p>
          </div>
        </div>
      </div> 
      
        <Services />
       <div>  <Portfolio />
       </div>
    <Port />
    </div>
   
  );
}
