import Image from "next/image";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function Portfolio() {
  return (
      <div className="mt-[100px] px-14">
        <div className="text-white flex flex-col gap-6 sticky h-fit">
          <div className="flex justify-between items-start gap-16 w-full">
          <div className="flex flex-col items-start w-1/2 sticky top-20 h-fit">
  <div className="flex items-center space-x-4 mb-6"> {/* Added mb-6 for spacing */}
    <span className="w-3 h-3 bg-white rounded-full"></span>
    <span className="text-left uppercase text-lg">Portfolio</span>
  </div>
  <h1 className="uppercase text-[40px] leading-tight">
    My Career <br />
    Journey
  </h1>
</div>


            <div className="flex flex-col w-full items-center px-8 overflow-y-auto max-h-screen">
             
              <div className="flex flex-col items-start w-full max-w-3xl ml-auto mr-auto pl-32">
                <div className="flex items-center space-x-4">
                  <span className="w-3 h-3 bg-white rounded-full"></span>
                  <span className="text-left uppercase text-lg">March 2024 - Present</span>
                </div>

                <h1 className="uppercase text-[40px] leading-tight mt-4">
                  Coronation Insurance
                </h1>
                <h2 className="text-[24px] mt-2 text-gray-400">UI / UX Design</h2>
                <p className="text-[18px] leading-[30px] mt-4 text-gray-300">
                  I am a product designer with over 5 years of experience designing digital <br />
                  solutions for people across various industries, including fintech, banking, and 
                  <br />e-commerce. I'm adept at collaborating with cross-functional teams 
                  <br />  (designers, developers) to bring ideas to life, leveraging data-driven research 
                  <br />   and a strong understanding of the space I’m building in.
                </p>
                <div className="border-t border-[#C8C8C8] w-full my-12"></div>
              </div>

              <div className="flex flex-col items-start w-full max-w-3xl ml-auto mr-auto pl-32">
                <div className="flex items-center space-x-4">
                  <span className="w-3 h-3 bg-white rounded-full"></span>
                  <span className="text-left uppercase text-lg">March 2024 - Present</span>
                </div>

                <h1 className="uppercase text-[40px] leading-tight mt-4">
                  Coronation Insurance
                </h1>
                <h2 className="text-[24px] mt-2 text-gray-400">UI / UX Design</h2>
                <p className="text-[18px] leading-[30px] mt-4 text-gray-300">
                  I am a product designer with over 5 years of experience designing digital <br />
                  solutions for people across various industries, including fintech, banking, and 
                  <br />e-commerce. I'm adept at collaborating with cross-functional teams 
                  <br />  (designers, developers) to bring ideas to life, leveraging data-driven research 
                  <br />   and a strong understanding of the space I’m building in.
                </p>
                <div className="border-t border-[#C8C8C8] w-full my-12"></div>
              </div>

  
              <div className="flex flex-col items-start w-full max-w-3xl ml-auto mr-auto pl-32">
                <div className="flex items-center space-x-4">
                  <span className="w-3 h-3 bg-white rounded-full"></span>
                  <span className="text-left uppercase text-lg">March 2024 - Present</span>
                </div>

                <h1 className="uppercase text-[40px] leading-tight mt-4">
                  Coronation Insurance
                </h1>
                <h2 className="text-[24px] mt-2 text-gray-400">UI / UX Design</h2>
                <p className="text-[18px] leading-[30px] mt-4 text-gray-300">
                  I am a product designer with over 5 years of experience designing digital <br />
                  solutions for people across various industries, including fintech, banking, and 
                  <br />e-commerce. I'm adept at collaborating with cross-functional teams 
                  <br />  (designers, developers) to bring ideas to life, leveraging data-driven research 
                  <br />   and a strong understanding of the space I’m building in.
                </p>
              </div>
            </div>
          </div>

          <div className="border-t border-[#C8C8C8] w-full my-10 py-12"></div>
        </div>
      </div>
  );
}
