import Image from "next/image";

export const metadata = {
  title: "Port",
  description: "Generated by create next app",
};

export default function Port() {
  return (
    <div className="px-14">
      <div className="text-white flex flex-col gap-6">
        <div className="flex justify-between items-start gap-16 w-full">
   
          <div className="flex flex-col items-start w-1/2 sticky top-20 h-fit">
          <div className="flex items-center space-x-4">
          <span className="w-3 h-3 bg-white rounded-full"></span>
          <span className="text-left uppercase text-lg">Portfolio</span>
        </div>
            <h1 className="uppercase text-[60px] leading-tight">
              What my <br /> clients/ <br /> colleagues <br /> say
            </h1>
          </div>

          <div className="flex flex-col w-full items-center px-8 overflow-y-auto max-h-screen">
            {/* Testimonial 1 */}
            <div className="flex flex-col items-start w-full max-w-4xl ml-auto mr-auto pl-40">
              <div className="flex items-center space-x-4">
                <span className="w-3 h-3 bg-white rounded-full"></span>
                <span className="text-left uppercase text-lg">01</span>
              </div>
              <p className="text-[18px] leading-[30px] mt-4 text-gray-300 text-left">
                I am a product designer with over 5 years of experience designing digital <br />
                solutions for people across various industries, including fintech, banking, and 
                <br />e-commerce. I'm adept at collaborating with cross-functional teams 
                <br />  (designers, developers) to bring ideas to life, leveraging data-driven research 
                <br />   and a strong understanding of the space I’m building in.
              </p>
              <div className="flex items-center space-x-4 mt-6">
                <div className="w-[72px] h-[72px] rounded-full overflow-hidden bg-gray-500">
                  <img src="/path-to-image.jpg" alt="Profile" className="w-full h-full object-cover" />
                </div>
                <div className="flex flex-col space-y-1">
                  <p className="text-[18px] text-white font-semibold">Brian Johnson</p>
                  <p className="text-[16px] text-gray-500">Digital Solutions Agency</p>
                </div>
              </div>
              <div className="border-t border-[#C8C8C8] w-full my-12"></div>
            </div>

            {/* Testimonial 2 */}
            <div className="flex flex-col items-start w-full max-w-4xl ml-auto mr-auto pl-40">
              <div className="flex items-center space-x-4">
                <span className="w-3 h-3 bg-white rounded-full"></span>
                <span className="text-left uppercase text-lg">01</span>
              </div>
              <p className="text-[18px] leading-[30px] mt-4 text-gray-300 text-left">
                I am a product designer with over 5 years of experience designing digital <br />
                solutions for people across various industries, including fintech, banking, and 
                <br />e-commerce. I'm adept at collaborating with cross-functional teams 
                <br />  (designers, developers) to bring ideas to life, leveraging data-driven research 
                <br />   and a strong understanding of the space I’m building in.
              </p>
              <div className="flex items-center space-x-4 mt-6">
                <div className="w-[72px] h-[72px] rounded-full overflow-hidden bg-gray-500">
                  <img src="/path-to-image.jpg" alt="Profile" className="w-full h-full object-cover" />
                </div>
                <div className="flex flex-col space-y-1">
                  <p className="text-[18px] text-white font-semibold">Brian Johnson</p>
                  <p className="text-[16px] text-gray-500">Digital Solutions Agency</p>
                </div>
              </div>
              <div className="border-t border-[#C8C8C8] w-full my-12"></div>
            </div>
            
            <div className="flex flex-col items-start w-full max-w-4xl ml-auto mr-auto pl-40">
              <div className="flex items-center space-x-4">
                <span className="w-3 h-3 bg-white rounded-full"></span>
                <span className="text-left uppercase text-lg">01</span>
              </div>
              <p className="text-[18px] leading-[30px] mt-4 text-gray-300 text-left">
                I am a product designer with over 5 years of experience designing digital <br />
                solutions for people across various industries, including fintech, banking, and 
                <br />e-commerce. I'm adept at collaborating with cross-functional teams 
                <br />  (designers, developers) to bring ideas to life, leveraging data-driven research 
                <br />   and a strong understanding of the space I’m building in.
              </p>
              <div className="flex items-center space-x-4 mt-6">
                <div className="w-[72px] h-[72px] rounded-full overflow-hidden bg-gray-500">
                  <img src="/path-to-image.jpg" alt="Profile" className="w-full h-full object-cover" />
                </div>
                <div className="flex flex-col space-y-1">
                  <p className="text-[18px] text-white font-semibold">Brian Johnson</p>
                  <p className="text-[16px] text-gray-500">Digital Solutions Agency</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="border-t border-[#C8C8C8] w-full my-12"></div>
      </div>
      <div className="border-t border-[#C8C8C8] w-full my-12"></div>
    </div>
  );
}
