import About from "../about/page";

export const metadata = {
    title: "Logo",
    description: "Generated by create next app",
  };
  
  export default function Logo() {
   return (
       <div className="text-[#C0C0C0] mt-[200px] px-6">
         <div className="max-w-full">
           <p className="uppercase text-[105px] leading-[1.2] font-extrabold">
             <span className="text-[#9C9C9C]">Hi, I’m Sam</span>uel um
             <span className="text-[#E0E0E0]">oru</span>
             <br />
             <span className="text-[#9C9C9C]">product de</span>signer <span className="text-[#E0E0E0]">and</span>
             <br />
             <span className="text-[#9C9C9C]">product str</span>ateg
             <span className="text-[#E0E0E0]">ist</span>
           </p>
         </div>
   
         <div className="mt-[150px]"></div> 
         <div className="text-[#C8C8C8] flex justify-between w-full text-[15px] leading-[32px] font-medium px-4">
           <p className="text-left max-w-md">
             Senior Product Designer with 6+ Years of Experience <br />
             Crafting Impactful Digital Solutions
           </p>
           <p className="text-right max-w-md">
             Based in Lagos, Nigeria <br />
             and open to work Worldwide
           </p>
         </div>
    <About />
       </div>
       
     );
  }
  